# User config
author: "Sandra Cortijo"
tagline: "Sandra Cortijo"
description: "Hola!! Bienvenida a mi galeria✨✨"
keywords: "Gallery, Portfolio, Art"
email: "sandra.cortijo24@gmail.com"
instagram: "https://www.instagram.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"
url: "https://sancortijo.netlify.app/"

# Developer
developerGH: "https://github.com/mavilam"

# Site config
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
